# Generated by Django 3.2.3 on 2021-05-23 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('policeStation', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfficerDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatchedDate', models.DateField()),
                ('policeStallName', models.CharField(max_length=250)),
                ('fieldOfficer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FieldOfficerManagment.fieldofficer')),
            ],
        ),
    ]
